DELETE FROM `bidlist`;
DELETE FROM `curvepoint`;
DELETE FROM `rating`;
DELETE FROM `rulename`;
DELETE FROM `trade`;
DELETE FROM `users`;

INSERT INTO `bidlist`
    ( `account`, `ask`, `ask_quantity`, `benchmark`, `bid`, `bid_list_date`, `bid_quantity`, `book`, `commentary`,
     `creation_date`, `creation_name`, `deal_name`, `deal_type`, `revision_date`, `revision_name`, `security`, `side`,
     `source_list_id`, `status`, `trader`, `type`)
VALUES
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    ( RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), null, RAND(), RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, null, RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID());

INSERT INTO `curvepoint` (`curve_id`, `term`, `_value`)
VALUES
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND()),
    (RAND() * 100, RAND(), RAND());

INSERT INTO `rating` (`fitch_rating`, `moodys_rating`, `order_number`, `sandprating`)
VALUES
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RAND() * 100, RANDOM_UUID());


INSERT INTO `rulename` (`description`, `json`, `name`, `sql_part`, `sql_str`, `template`)
VALUES
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID());

INSERT INTO `trade`
    (`account`, `benchmark`, `book`, `buy_price`, `buy_quantity`, `creation_date`, `creation_name`,
     `deal_name`, `deal_type`, `revision_date`, `revision_name`, `security`, `sell_price`, `sell_quantity`, `side`,
     `source_list_id`, `status`, `trade_date`, `trader`, `type`)
VALUES
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), null, RANDOM_UUID(), RANDOM_UUID(), RANDOM_UUID(), null, RANDOM_UUID(), RANDOM_UUID(), RAND(), RAND(), RANDOM_UUID(), RAND(), RANDOM_UUID(),null, RANDOM_UUID(), RANDOM_UUID());

INSERT INTO `users` (`fullname`, `password`, `role`, `username`)
VALUES
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID()),
    (RANDOM_UUID(), CONCAT('Aa1!', RANDOM_UUID()), RANDOM_UUID(), RANDOM_UUID());

